#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copernicus.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Copernicus;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LoginPartial.cshtml")]
    public partial class LoginPartial : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LoginPartial()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_LoginPartial.cshtml"
 if (Request.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("    <li");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"right\"");

WriteLiteral("><a");

WriteLiteral(" href=\"/Account/Manage\"");

WriteLiteral(" title=\"Account\"");

WriteLiteral("><img");

WriteLiteral(" src=\"/Content/Images/Account2.png\"");

WriteLiteral(" title=\"Account\"");

WriteLiteral(" alt=\"Account\"");

WriteLiteral(" /></a></li>\r\n    </li>\r\n");

            
            #line 5 "..\..\Views\Shared\_LoginPartial.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"right\"");

WriteLiteral("><a");

WriteLiteral(" href=\"/Account/Login\"");

WriteLiteral(" id=\"loginLink\"");

WriteLiteral(" title=\"Login\"");

WriteLiteral("><img");

WriteLiteral(" src=\"/Content/Images/Login2.png\"");

WriteLiteral(" title=\"Login\"");

WriteLiteral(" alt=\"Login\"");

WriteLiteral(" /></a></li>\r\n");

            
            #line 7 "..\..\Views\Shared\_LoginPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
