#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copernicus.Views.Admin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Copernicus;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Admin/Plugins.cshtml")]
    public partial class Plugins : System.Web.Mvc.WebViewPage<IEnumerable<Ironman.Models.Plugins.Plugin>>
    {
        public Plugins()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Admin\Plugins.cshtml"
  
    ViewBag.Title = "Installed Plugins";

            
            #line default
            #line hidden
WriteLiteral("\r\n<form");

WriteLiteral(" action=\"/Admin/Plugins\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n    <h1>Available Plugins</h1>\r\n    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n        <tr>\r\n            <th></th>\r\n            <th>Name</th>\r\n            <t" +
"h>Description</th>\r\n        </tr>\r\n    \r\n");

            
            #line 15 "..\..\Views\Admin\Plugins.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Admin\Plugins.cshtml"
     foreach (Ironman.Models.Plugins.Plugin item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("name", Tuple.Create(" name=\"", 463), Tuple.Create("\"", 484)
            
            #line 19 "..\..\Views\Admin\Plugins.cshtml"
, Tuple.Create(Tuple.Create("", 470), Tuple.Create<System.Object, System.Int32>(item.PluginID
            
            #line default
            #line hidden
, 470), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 485), Tuple.Create("\"", 504)
            
            #line 19 "..\..\Views\Admin\Plugins.cshtml"
, Tuple.Create(Tuple.Create("", 490), Tuple.Create<System.Object, System.Int32>(item.PluginID
            
            #line default
            #line hidden
, 490), false)
);

WriteLiteral(" />\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\Admin\Plugins.cshtml"
           Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Admin\Plugins.cshtml"
           Write(item.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");

            
            #line 28 "..\..\Views\Admin\Plugins.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    </table>\r\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" onclick=\"form.action=\'/Admin/UpdatePlugins\'\"");

WriteLiteral(" value=\"Update Plugins\"");

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" onclick=\"form.action = \'/Admin/UninstallPlugins\'\"");

WriteLiteral(" value=\"Uninstall Plugins\"");

WriteLiteral(" />\r\n</form>");

        }
    }
}
#pragma warning restore 1591
