#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copernicus.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Copernicus;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("featured", () => {

WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ten columns\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(" id=\"ProjectsList\"");

WriteLiteral(">\r\n                <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                    <h3>Current Projects</h3>\r\n                </hgroup>\r\n    " +
"            <ol");

WriteLiteral(" class=\"round\"");

WriteLiteral(" data-bind=\"visible: toggle, foreach: projects\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" data-bind=\"html: Text\"");

WriteLiteral(">\r\n                    </li>\r\n                </ol>\r\n            </div>\r\n        " +
"</div>\r\n    </section>\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"six columns\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(" id=\"newCompaniesAndPeople\"");

WriteLiteral(">\r\n        <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n            <h3>New Companies and Contacts</h3>\r\n        </hgroup>\r\n        <o" +
"l");

WriteLiteral(" class=\"round\"");

WriteLiteral(" data-bind=\"visible: toggle, foreach: newCompaniesAndPeople\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" data-bind=\"html: Text\"");

WriteLiteral(">\r\n            </li>\r\n        </ol>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(" id=\"recentUpdates\"");

WriteLiteral(">\r\n        <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n            <h3>Recent Updates</h3>\r\n        </hgroup>\r\n        <ul");

WriteLiteral(" data-bind=\"visible: toggle, foreach: recentUpdates\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" data-bind=\"html: Text\"");

WriteLiteral(">\r\n            </li>\r\n        </ul>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"four columns\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(" id=\"activities\"");

WriteLiteral(">\r\n        <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n            <h3>Activities</h3>\r\n        </hgroup>\r\n        <ul");

WriteLiteral(" data-bind=\"visible: toggle, foreach: upcomingActivities\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" data-bind=\"html: Text\"");

WriteLiteral(">\r\n            </li>\r\n        </ul>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
