#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copernicus.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Copernicus;
    
    #line 1 "..\..\Views\Account\Manage.cshtml"
    using Copernicus.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Account\Manage.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Manage.cshtml")]
    public partial class Manage : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Manage()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Manage.cshtml"
  
    ViewBag.Title = "Manage Account";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Views\Account\Manage.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n\r\n<p");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Account\Manage.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Account\Manage.cshtml"
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\Manage.cshtml"
         if (ViewBag.HasLocalPassword)
        {
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\Manage.cshtml"
       Write(Html.Partial("_ChangePasswordPartial"));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\Manage.cshtml"
                                                   
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\Manage.cshtml"
       Write(Html.Partial("_SetPasswordPartial"));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\Manage.cshtml"
                                                
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <section");

WriteLiteral(" id=\"externalLogins\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Account\Manage.cshtml"
       Write(Html.Action("RemoveAccountList"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\Account\Manage.cshtml"
       Write(Html.Partial("_ExternalLoginsListPartial", new { Action = "LinkLogin", ReturnUrl = ViewBag.ReturnUrl }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </section>\r\n    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Account\Manage.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
